group=com.ktross
version=2.0.0-SNAPSHOT
javaVersion=25
paperApiVersion=26.2.build.111-stable
spigotApiVersion=26.2-R0.1-20260808.232455-11
junitVersion=5.14.3
jetbrainsAnnotationsVersion=26.1.0

org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.warning.mode=all
org.gradle.jvmargs=-Xmx1G -Dfile.encoding=UTF-8
